//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int idLibro { get; set; }
        public string nomLibro { get; set; }
        public string ISBN { get; set; }
        public string autor { get; set; }
        public string editorial { get; set; }
        public string comentario { get; set; }
    }
}
