//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        public int idCliente { get; set; }
        public int idLibro { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
